services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
      - ./backups:/backups
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=sectorfive_db
    networks:
      - sectorfive_network
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=sectorfive_db
      - CORS_ORIGINS=*
      - UPLOAD_PATH=/app/uploads
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backups:/app/backups
    networks:
      - sectorfive_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8001/api
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - sectorfive_network
      
volumes:
  mongo_data:

networks:
  sectorfive_network:
    driver: bridge