version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=sectorfive_db
      - CORS_ORIGINS=*
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - "8001:8001"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "80:80"
volumes:
  mongo_data: